name: "Development CI"

on:
  push:
    branches:
      - main

jobs:
  docker-image-build-publish:
    name: Build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ruhulinfo/myapp:${{ github.sha }}

      - name: Push docker image
        run: docker push ruhulinfo/myapp:${{ github.sha }}
